### ISSUE TITLE
Make the gestures more responsive

### ISSUE THREAD

**Issue by ZeppLu** [bulletmark/libinput-gestures#119]
I find that no action will be taken unless my fingers leave off my touchpad, which makes it seem not so responsive (you know, on Mac OS or Windows gestures are recognized as soon as fingers movement reaches a threshold, like pinch, rotate, etc).

So what about adding a similar functionality, it seems trivial cause output of `libinput debug-events` has a time field (I tried by myself but sadly I'm not familiar with Python).

**Comment by bulletmark** [comment]
Look at the output of `libinput debug-events`. A gesture as reported by libinput has a BEGIN event, many UPDATE events, and then a final END event. This utility is very simple and merely actions a configured gesture after the END event because it is only then when the final gesture direction, distance (and angle for extended gestures) is decided. In fact, you can cancel an event by breaking your fingers away etc and then the END event is marked by libinput as cancelled in which case this utility ignores it. So, in short, this utility actions gestures exactly how they are defined by libinput.  What you ask for would be possible to implement but I would not be keen to change something so fundamental.

I previously had a Mac but don't find the usability much different myself. E.g. swipe ups and downs to change workspace require only a very short quick (short-travel) flick of 3 or 4 fingers so the difference is barely noticeable IMHO.

Python is easy to learn. You could try to fork this repo and implement that change.
