### ISSUE TITLE
xdotool alternative?

### ISSUE THREAD

**Issue by amivaleo** [bulletmark/libinput-gestures#120]
Hi,
do you an alternative for the command "xdotool key" on gnome wayland session?

Thanks. :)

**Comment by bulletmark** [comment]
Please read the Wayland And Other Notes section of the README and let me know which part is not clear. By design, there is no xdotool equivalent for Wayland and there likely never will be. Use Google if you are interested in pursuing why.

**Comment by amivaleo** [comment]
Thank you for your reply.
I did read the README already, but I couldn't find the anwser to my question.
I would like to set this command:
"gesture swipe up 3 wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz"
Following your README, "wmctrl" should work fine, but it actually works only for guake, as far as I've seen.
That's why I asked about an alternative for "xdotool key", since I thought I could avoid to use wmctrl for window maximizing if I set super+UP shortcut.

**Comment by bulletmark** [comment]
The default configuration of this utility uses `wmctrl` to send workspace switch commands to the Wayland compositor (e.g. GNOME Mutter). This works atm by a quirk because it appears XWayland has support to pass these particular desktop commands through. However, given Wayland much stricter security constraints, it is not surprising that you can not send commands to arbitrary windows (other than for apps that are stilling running under X, like guake as you mention).
