### ISSUE TITLE
Overrides natural scrolling with two fingers

### ISSUE THREAD

**Issue by piggyslasher** [bulletmark/libinput-gestures#124]
Is this what you mean by configuring swipe in the `conf` file for natural scrolling?

Would it be possible to have a few sample lines, but commented for natural scrolling? I tried, but could not get it to change. I'm referring to two finger scroll (vertical and horizontal)

**Comment by bulletmark** [comment]
I am not sure what you are asking but most people nowadays prefer 2 finger "natural" swipe scrolling direction instead of the "reverse" swipe scrolling direction which prevailed some time ago. None of this has anything to do with `libinput-gestures` because it only actions what `libinput` calls swipe gestures, which are always 3 or more fingers. If however, you really prefer to configure your 2 finger scrolling direction in the old reverse way (i.e. via your DE's touchpad/mouse settings), then it is very likely you also prefer to configure your 3 or 4 finger swipes in this` libinput-gestures` utility to work in same reverse way as well, i.e. swap the left <--> right and up <--> down commands in the example default config file.

**Comment by bulletmark** [comment]
No response from OP.
