### ISSUE TITLE
Enable click and tab gestures as well as click actions

### ISSUE THREAD

**Issue by romanlehnert** [bulletmark/libinput-gestures#132]
Currently migrating from Mac to Linux. libinput-gestures saved my ass, since i used bettertouchtool a lot. Thanks for the awesome job. 

However, do you see a chance from a technical perspective to allow multi finger tap and swipe gestures? 

An example for a very useful binding is: 
* `3 finger tap` to `ctrl + click` (open link in new background tag in chrome)
* `3 finger click` to `ctrl + w` (close current tab)

**Comment by bulletmark** [comment]
A 3 finger tap is not a libinput gesture so is not processed by this application. However, you can already manage your chrome tabs completely from your touchpad using the extended gestures as documented in the main [README](https://github.com/bulletmark/libinput-gestures/blob/master/README.md) here and in the default `libinput-gestures.conf`. The example swipes allow you to jump between tabs and close/reopen tabs. I use all those (i.e. 8 swipe angles over 360 degrees instead of the normal 4) and they work pretty well.
