### ISSUE TITLE
Non-blocking app launch

### ISSUE THREAD

**Issue by cunidev** [bulletmark/libinput-gestures#135]
Hello, I'm developing a GUI frontend for libinput-gestures, but I'm experiencing problems when launching GUI apps (such as budgie-run-dialog or vlc), as the process seems to lock libinput-gestures and queue all following events. The & at the end of the command doesn't change the situation. Is running it in foreground a wanted choice or a bug? Why isn't shell=False in the Popen line?

Just asking. Thanks for the great tool! :)

**Comment by bulletmark** [comment]
`shell` is already `False` in the Popen call, but that is not related to your issue.

I just pushed a new branch called _daemon_. Please try that and let me know how it goes. As per the change to the README there, you need to install `python[3]-daemon`.

**Comment by cunidev** [comment]
Wow, that was fast, thank you!

The situation hasn't apparently changed though :(

Some logs and the config file to replicate the issue:
```r@r:~/gestures$ libinput-gestures -v
libinput-gestures: session pantheon+x11 on Linux-4.13.0-26-generic-x86_64-with-elementary-0.4.1-loki, python 3.5.2, libinput 1.6.3

libinput-gestures: using ~/.config/libinput-gestures.conf with 11 gestures
libinput-gestures: device /dev/input/event8: Elan Touchpad
```


libinput-gestures.conf

```
# Generated by Gestures 0.1.1  -->  https://github.com/cunidev/gestures
# Manual editing might result in data loss!


# Invalid lines

# Unsupported lines

#Gestures
gesture pinch in 2 xdotool key Ctrl+minus
gesture pinch out 2 xdotool key Ctrl+plus
gesture swipe down 4 budgie-run-dialog
gesture swipe up 4 /opt/gestures/gestures
gesture swipe left 4 xdotool key ctrl+alt+Right
gesture swipe right 4 xdotool key ctrl+alt+Left
gesture pinch clockwise 2 vlc &
gesture pinch anticlockwise 2 vlc
```


The version should be the latest from the Daemon branch:
```
r@r:~/gestures$ cat /usr/bin/libinput-gestures
#!/usr/bin/env python3
'Read gestures from libinput touchpad and action shell commands.'
# Mark Blakeney, Sep 2015

# Import system modules
import os, sys, argparse, subprocess, shlex, re, getpass, fcntl, platform, math
from collections import OrderedDict
from pathlib import Path
from distutils.version import LooseVersion as Version

# Import 3rd party modules
import daemon

PROG = Path(sys.argv[0]).stem
[...]
```


Thank you.

**Comment by bulletmark** [comment]
Forget about that daemon branch as I realize that approach is not going to fix anything.

I'm not really clear about the problem you are describing and also not clear whether the problem is with `libinput-gestures`, or your GUI. You should only be interacting with `libinput-gestures` using `libinput-gestures-setup`, e.g. your user changes/adds a gesture line, your GUI writes a new `~/config/libinput-gestures.conf`, and then your GUI should do a `libinput-gestures-setup restart` to enable the new config file. Is that what you are doing?

**Comment by cunidev** [comment]
Yes, that should be exactly what my gui is doing, the conf file works same
without the gui as it basically only edits it and `libinput-gestures-setup
restart`-s it. But if I set it to open any GUI app or other process that
requires time to complete, it queues the next events for when the process
is terminated, as should be reproduced in the sample .conf file I provided
(opening vlc). Popen should do that asynchronously "in background" already,
provided shell=False and all needed parameters are given. But Popen just
opens one process in background, and pipes the others behind afaik. Maybe
os.spawnl could be a better replacement?

Thanks for the quick reply!

**Comment by bulletmark** [comment]
I just realized that you are simply saying that you can not configure a long running process as a gesture action because it blocks. This issue has nothing to do with your GUI app etc.

Note the 2nd last paragraph in the CONFIGURATION section of the main README. If you have anything sophisticated you want to run as the command then you need to create a wrapper shell script. E.g. in this case you want to configure your gesture to run a `vlc_start` somewhere on your path and that script should be something like:

~~~~
#!/bin/bash
exec nohup vlc &>/dev/null &
~~~~

**Comment by cunidev** [comment]
I see. Maybe I could write a workaround for that in my GUI then. Thanks anyway :)
