### ISSUE TITLE
Is there a key map for mouse wheel up/ down?

### ISSUE THREAD

**Issue by alexnickle92** [bulletmark/libinput-gestures#136]
I've been trying to figure out a way to have the pinch to zoom in and out but I'm not sure if there is a key map for the mouse wheel.

**Comment by bulletmark** [comment]
What to do when you pinch in and out is generally dependent on the application so that is why DE's and libinput generally leave it for the application to implement. E.g. on my GNOME (Wayland) system I don't map PINCH gestures at all using `libinput-gestures` but applications like the stock image viewer already implement zooming using PINCH gestures. Does it not work for you?

**Comment by alexnickle92** [comment]
I want to able to use pinch zoom for the whole desktop and within all applications. (ex like on a mac)

**Comment by bulletmark** [comment]
Actually, as per the comment in `libinput-gestures.conf`, since GNOME 3.24 pinch is already implemented natively to zoom in/out of the GNOME overview, at least on Wayland. If you are still using Xorg then there is an example configuration there to use.
