### ISSUE TITLE
How to name = and - in xdotool?

### ISSUE THREAD

**Issue by michaldybczak** [bulletmark/libinput-gestures#144]
Sorry for spamming here but I'm playing with libinput-gestures and what it can do.
There is a magnifier effect in Plasma, by default zoom in is meta+=, zoom out is meta+-.

The issue is: I can't find a word which xdotool would accept as equal sign or minus. In fact, it has to be minus from the number row, not from number pad so there has to be some distinction.

Anyway, I wanted to use pinch with those zoom effects.

I've been searching for key names but all I found was EQUALS and MINUS, which are not working and something has to work. Do you know what is the proper name for those keys or where to look?

If there is some list of key names, please add this to libinput-gestures documentation (on in conf). Thanks!

**Comment by michaldybczak** [comment]
I found a command:

`xev -event keyboard`

It can name many key names, but still I get no luck. It seems that some keys are somewhat not xdotool digestible. = and - signs seem to be one of them.
I tried to assign my custom shortcut (with easier keys) but xdotool seem to accept only system default ones. So it seems that some things may not be possible at the moment?

`xdotool key meta+equal
`
 don't work in terminal although the xev -event keyboard command shows the name "equal" for = sign.I get over 5k results with it... so this xdotool seems to be complicated and very badly documented and that again is not your fault. So I won't hold it against you if you close this topic.

**Comment by bulletmark** [comment]
Sorry, discussing `xdotool` is not relevant here.

**Comment by bulletmark** [comment]
I've never invested much time in `xdotool` given it doesn't (and can never) work with Wayland so is pretty much a dead end.

**Comment by michaldybczak** [comment]
Yeah, but still Wayland seems to be a years away and its not usable for nvidia users and is still immature. But hopefully there will be a tool that will work like xdotool or better but be applicable for wayland as well.

Still, I see huge amount of progress over the last year when gestures worked on a whim but now they are pretty reliable. All I did was: I updated system (rolling release) and moved to latest kernel (currently 4.16). Manjaro is pretty stable for me on various computers so installs last indefinitely so far and on such old installs I observed how gestures detection improved. This adds so much to workflow! It feels matured now.

I really believe that libinput should be a basic part of the most distros and someone should write a simple GUI for it ;). I know that it was originally a workaround, a temporal bridge but as you see, it serves well and will serve well probably for incoming years :D.
Thanks again for this amazing piece of work! We enjoy it a lot!

**Comment by bulletmark** [comment]
18 months ago my distro (Arch) updated the stock packages for GNOME from 3.20 to 3.22 where the default session changed from Xorg to Wayland and since I use auto-login I have to say that I didn't even realize for the first day that I was running on Wayland! That is how good it was then and it has only matured since so to say it is "years away" is plainly wrong. I have used Wayland on my PC and notebook since that time without any issues. I only use Intel graphics though.

If you read the 2nd paragraph of the README here you will see that I only ever intended this utility as a "temporary hack" because I assumed that GNOME/KDE etc would soon give us better configuration facilities for gestures, like I  had on my previous Mac many many years ago, at least since libinput. For some odd reason we have not yet seen this happen.
