### ISSUE TITLE
Touchscreen compatibility

### ISSUE THREAD

**Issue by Exel232** [bulletmark/libinput-gestures#15]
Currently gestures only work for touchpads, as touchscreens send different signals to the program. Would it be possible to add touchscreen support?

**Comment by bulletmark** [comment]
No sorry. This is just a small and simple app which parses the gestures interpreted by the libinput's `libinput-debug-events` utility. Since libinput does not interpret gestures on touchscreens as per https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#gestures_touchscreens, there is nothing I can do about this.
