### ISSUE TITLE
libinput-tools 1.11.1-1 broke libinput-gestures

### ISSUE THREAD

**Issue by steinwayer** [bulletmark/libinput-gestures#159]
The update of libinput (from 1.11.0-1 to 1.11.1-1) broke libinput-gestures. Output of "libinput-gestures-setup restart":

Command '['libinput', 'list-devices']' died with <signals.sigsegv: 11=""></signals.sigsegv:>

Output of "libinput list-devices":

[1] 12303 segmentation fault (core dumped) libinput list-devices

**Comment by bulletmark** [comment]
I have tried to ensure new bugs would include the output of `libinput-gestures -l` but sadly it seems I have still failed here. Genuine question - how did you miss that?

This bug occurred on Arch Linux on June 19 due to a bug in stock libinput when it upgraded from 1.11.0-1 -> 1.11.1-1. It was fixed quickly after in upstream libinput git master and the patch was merged to Arch and released on Arch as 1.11.1-2 on 23 June. See bug #158, https://gitlab.freedesktop.org/libinput/libinput/issues/50, and https://bugs.archlinux.org/task/59082.

What distro are you using? Note `libinput-gestures -l` would have told me that.

**Comment by steinwayer** [comment]
My apologies Mark, i didn't know it was fixed, i started having this issue on my machine today, digged a little bit around online to find a solution and noticed it was mentioned in a forum but didn't see it on github. So i thought about posting it.

Anyway here the result of my libinput-gestures -l
libinput-gestures: session plasma+x11 on Linux-4.16.0-kali2-amd64-x8
6_64-with-Kali-kali-rolling-kali-rolling, python 3.6.6rc1+, libinput
1.11.1
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up 3 xdotool key ctrl+alt+9
swipe down 3 xdotool key ctrl+alt+9
swipe left xdotool key alt+Left
swipe left 4 xdotool key ctrl+alt+m
swipe right 4 xdotool key ctrl+alt+n
swipe up 4 xdotool key ctrl+alt+j
swipe down 4 xdotool key ctrl+alt+b
swipe right xdotool key alt+Right
pinch in xdotool key super+s
pinch out xdotool key super+s
Command '['libinput', 'list-devices']' died with <Signals.SIGSEGV: 1
1>.
Can not see any devices, did you add yourself to the input group and
log out/in?
Could not determine touchpad device.

now, it's not related to the user's input group, i added the user to input group(it was working until this morning).

thanks

**Comment by bulletmark** [comment]
Looks like your Distro Kali recently updated to libinput 1.11.1-1 as Arch did so you could open a bug to petition them to add the upstream patch like I did for Arch at https://bugs.archlinux.org/task/59082
