### ISSUE TITLE
Running libinput-gestures in a systemd service

### ISSUE THREAD

**Issue by leewdch** [bulletmark/libinput-gestures#163]
Apparently I can't use `libinput-gestures-setup restart` as root

> Usage:
> As root: sudo libinput-gestures-setup install|uninstall
> As user: libinput-gestures-setup start|stop|restart|autostart|autostop|status

I have issues with my laptop and I need to reload my touchpad drivers after resuming from sleep mode. Thing is I also need to restart libinput-gestures! I can't do that inside a service apparently. Do I need to add an additional systemd service setting myself as user or maybe there is a warkaround?

**Comment by bulletmark** [comment]
Please note step 8 of the troubleshooting section.

**Comment by bulletmark** [comment]
No response? I see you are still posting actively on a related issue on the Arch forums so it seems you are running Arch. I thus assume your system is up to date and thus you are running the current Arch kernel and libinput versions (`libinput-gestures -l` would have told me all this).

The sleep issue is not to do with this package. See my comment at https://github.com/bulletmark/libinput-gestures/issues/160#issuecomment-402378157. As there, I suggest you update your BIOS because `libinput debug-events` does work fine through a suspend for most people, including myself.

**Comment by bulletmark** [comment]
BTW, I should add that `libinput-gestures` runs in a specific user's environment (for 1 or more users) and is started from `~/.config/autostart` etc. Thus you can't run it or the service script as root because which user would it be acting for? However, you can run a systemd service as a user (`User=`) or you can run a systemd service [in User Mode](https://wiki.archlinux.org/index.php/Systemd/User).

**Comment by barryridge** [comment]
@leewdch Just adding some breadcrumbs for others here. I found it basically impossible to get this working on a 6th Gen X1 Carbon using either systemd system-sleep scripts or systemd user mode services, so I resorted to a different approach.  Rather than attempting to restart libinput-gestures in this way when entering/exiting a suspend state, we can assume that exiting a suspend state invokes the lock screen, and run a script that monitors for that and executes the libinput-gestures restart when that happens. This works because once the lock screen is up, gdm is certainly also up with the appropriate user account/display combo.

Name the following script `libinput-gestures-restart` or similar, make it executable, place it somewhere appropriate, e.g. `/home/$USER/bin`, and run `/home/$USER/bin/libinput-gestures-restart &` in your startup applications and you should be good to go:

```bash
#!/bin/bash

dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" |
  while read x; do
    case "$x" in
      *"boolean true"*) libinput-gestures-setup restart;;
      *"boolean false"*) libinput-gestures-setup restart;;
    esac
  done

exit 0
```

**Comment by NitroBAY** [comment]
I don't like the while read. I didnt have gnome so I created a .sh file which simply calls libinput-gestures-setup restart and other things I need at bootup like touchegg which is called by my systemd file.
I feel like barryridge solution is not as elegant as it can get.
