### ISSUE TITLE
Non-installation commands must be run as your own user

### ISSUE THREAD

**Issue by Elvis-J** [bulletmark/libinput-gestures#172]
I have the infamous "Non-installation commands must be run as your own user." problem
I've read a bunch of threads trying to solve the problem but it's a no go.
- run gpassws, user added to the group
- log out/ log in, restart, no effect
- all dependencies installed
- both -r and -d work without a problem, gestures are registered
- journalctl | grep libinput-gestures returns:
kali gnome-software[1335]: Failed to find one package for libinput-gestures.desktop, /usr/share/applications/libinput-gestures.desktop, [0]
no idea what package this might be.
Also I wonder if it might be a problem that the user is root?

Thx in advance
```
libinput-gestures: session gnome+x11 on Linux-4.16.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling, python 3.6.6, libinput 1.12.0
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/event1: ETPS/2 Elantech Touchpad

**Comment by bulletmark** [comment]
Please fix up your post above. You have pasted your code as text and your text as code.

I'm not actually sure what you are trying to say here. What is the actual problem? If you are really running your desktop environment as root then certainly you should never do that for many other reasons other than this utility.

**Comment by Elvis-J** [comment]
I know that running as a root is not a good practice but it's a default setting on Kali and I'm too lazy to change it.
The problem is in the title.
Once I type "libinput-gestures-setup start" I get "Non-installation commands must be run as your own user" as a reply.
My question is if this is happening because I run it as a root or something else.
And how to troubleshoot it.

**Comment by bulletmark** [comment]
I doubt any Linux distro would suggest/propose/advise anybody to log in to a graphical desktop environment  as root. In fact the [Kali Installation Procedure](https://docs.kali.org/installation/kali-linux-hard-disk-install) makes you create a normal user in steps 6 and 7. Log in as that user.

**Comment by Elvis-J** [comment]
Created additional user and added it to the sudoers.
Now it works. Kinda.
The lag is considerable and gestures tend to be misinterpreted.
Also, not sure why the default swiping settings are reversed,
Putting all this aside, my question still remains: is it possible to run this as root?
I have a bunch of stuff in my root home folder, desktop, downloads etc, my Firefox extensions are installed, shortcuts set and there would be a lot of work to do this again (for the other user).
Thx!

**Comment by bulletmark** [comment]
Nobody else has said "The lag is considerable and gestures tend to be misinterpreted", nor has anybody wanted to pursue running their DE as root once they are informed it should never be done. E.g see https://fedoraproject.org/wiki/Enabling_Root_User_For_GNOME_Display_Manager as one of many examples. Saying that, who am I to force users on this so I just added commit afc909e9b729280938e41d95c471062cf230040a to allow it. Add `-r` to your `libinput-gestures-setup` commands.

The default swipe settings match the most common touchpad "natural" scrolling scheme. Most systems (Linux/Mac/Windows) allow you to change your touchpad to use the original "reverse" scrolling which we all typically used before about 2011 (when Apple changed it to "natural" and most others eventually followed because it is ultimately a more sensible choice). If you want to use "reverse" scrolling then just swap the swipe directions in your custom config.

**Comment by Elvis-J** [comment]
I can confirm that it's working.
Guess you should add this to the documentation for the lost sheep like me :)
Thx!

**Comment by bulletmark** [comment]
The last thing I want to do is encourage anybody to run that setup script as root so I will leave it as  is.
