### ISSUE TITLE
relying on non-stable interfaces

### ISSUE THREAD

**Issue by whot** [bulletmark/libinput-gestures#18]
I just found a link to this repo somewhere (already forgot where, sorry). This isn't a bug just yet but a heads-up, the tools libinput provides (libinput-list-devices and libinput-debug-events) are for human consumption, their output is not stable and it may change at any time.

As I said, this is just a heads up/warning.

**Comment by bulletmark** [comment]
Yes Peter your man pages etc have always stated that so I have always been very cognizant of it. As the README here says, this utility was/is only ever intended to be used temporarily until the DE's action libinput gestures natively but that seems slow going. I created this little "hack" utility essentially for myself but it has become surprisingly popular.

Since Arch linux gets every libinput release and always gets it within a couple of days I make sure I immediately run this utility in debug mode every time a new release appears to check it maintains compatibility. I also read your release notes thoroughly. So feel free to go ahead and break this(!) with whatever changes you do to libinput as I will accommodate this code. :)

FYI, I originally coded this in Python only as a proof of concept and was intending to re-code it in C using the libinput API which is the way it should be done of course but this "proof" code seems to work so efficiently that I never bothered implementing it the other way.

I'll leave this bug open here given it perhaps is a "flaw" in the current design.

**Comment by whot** [comment]
if you're really keen you could look at doing python bindings for libinput ;)

**Comment by rightaway** [comment]
> this utility was/is only ever intended to be used temporarily until the DE's action libinput gestures natively but that seems slow going

Would this project continue to be maintained when DE's will support libinput gestures, for people who aren't using a DE? Or will those people need to find another alternative at that time for gestures?

**Comment by bulletmark** [comment]
I will keep maintaining it. If I don't then somebody will fork it and continue.

I use stock Arch with GNOME which upgraded to v3.22 this week and now uses Wayland by default rather than Xorg. Libinput-gestures relies on `xdotool` which can not run on Wayland and there is no equivalent so I myself my not even use this utility from here on. Saying that, even though GNOME+Wayland runs extremely well, I am shocked to find that it does not provide any gestures (at least for my trackpad) so I may even switch back to Xorg just to continue using libinput-gestures.

**Comment by joshuap** [comment]
I've switched back to xorg temporarily for libinput-gestures. It would be awesome if libinput supported native configuration of similar gestures under Wayland.

**Comment by whot** [comment]
Fedora 24 here: eog supports pinch-to-zoom on my touchpad touch admittedly that's the only application I could find quickly that does. The issue with gestures is that unlike xdotool that hooks into key events etc. GTK gestures are now integrated into the toolkit. but that requires applications to support them. It's not a short-term fix but long-term it's maintainable and the correct approach to integration.

**Comment by bulletmark** [comment]
I have discovered that GNOME on Wayland provides a 4 finger gesture to switch workspaces but that it lacks the page popup compared to the keyboard shortcut and can not be configured. I raised GNOME bug https://bugzilla.gnome.org/show_bug.cgi?id=773008 about it.

**Comment by GNOME-IS-LIFE** [comment]
GNOME on Wayland now also has a built-in three finger pinch gesture to show all open windows, so maybe you could add that to the README as well? :smile: 
(big fan of your work!!)

**Comment by bulletmark** [comment]
@GNOME-IS-LIFE thanks for that. Surprisingly, that was added back in 3.24 but I must have missed that in the release notes and have never seen any mention of it. I have just added commit 1875bdcae69dee62fc569f61fad858ae4e59b82e to note this. I also changed the default pinch commands to use `xdotool` because the generic default gestures would otherwise clash on Wayland.

**Comment by Coffee2CodeNL** [comment]
https://github.com/Coffee2CodeNL/gebaar-libinput

Working on a little something :-)

**Comment by bulletmark** [comment]
I am closing this given it is 3 years old and the `libinput` tools have proven to be perfectly stable over that time so this turned out to be a non-issue.

**Comment by whot** [comment]
well..... :)

I have several patches in the pipe that will change the output for `POINTER_AXIS` events and I think I've changed other events since. Including changing from `libinput-debug-events` to `libinput debug-events`. It just turned out that the events you relied on so far didn't need changing yet.

But yeah, it's not really necessary to keep a bug open here as long as you're aware that it may break at any time.
