### ISSUE TITLE
Respect the xinput transformation matrix setting

### ISSUE THREAD

**Issue by peey** [bulletmark/libinput-gestures#200]
Config output: 
```
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-43-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3

Gestures configured in ~/.config/libinput-gestures.conf:
swipe right      3 xdotool key ctrl+alt+Right
libinput-gestures: device /dev/input/event16: ELAN1300:00 04F3:3057 Touchpad
```

**Describe the issue**

I'm not having any problems with running libinput-gestures normally. However sometimes I like to rotate my screen, and so I rotate my touchpad to go with it. This is achieved by setting a coordinate transformation matrix ([a guide on ubuntu wiki](https://wiki.ubuntu.com/X/InputCoordinateTransformation)), somewhat like this:

```
xinput set-prop $touchpad_name --type=float "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1
```

Which essentially rotates your touchpad 90 degrees clockwise: meaning now my mouse pointer moves right if I move my finger down.

Is there a way for libinput-gesture to also respect this setting while detecting gestures? So that a down swipe is actually taken to be a right swipe

**Comment by bulletmark** [comment]
Can you please paste the output of `libinput list-devices` for that touchpad?

**Comment by peey** [comment]
I think you meant  `libinput-list-devices`

```
Device:           ELAN1300:00 04F3:3057 Touchpad
Kernel:           /dev/input/event16
Group:            7
Seat:             seat0, default
Size:             103.48x69.06mm
Capabilities:     pointer
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

**Comment by bulletmark** [comment]
Actually, I did mean `libinput list-devices` - because I didn't notice you were running an ancient version of libinput which is over two years old and six major releases ago! From libinput 1.8 they changed `libinput-list-devices` to `libinput list-devices`.

See that `rotation` option listed in your output? I think you can set a configure option to rotate some touchpads 90, 180, 270 degrees etc, but that does not seem like it would work for you.

If you have rotated your touchpad 90 degrees, then can't you just switch in an alternative `libinput-gestures.conf` file with that command configured as `swipe up 3 xdotool key ctrl+alt+Right`?

**Comment by peey** [comment]
Yeah, it's possible to switch the `libinput-gestures.conf` file. I might have libinput from whatever version it is in ubuntu 16's caches.

I don't know the exact relationship of the `xinput` with my system though. I thought it was at a lower level than `libinput-gesture` or `libinput`, so that my raw touches go to `xinput` and whatever it spits out goes to rest of the system, or that its configuration is a way to centrally configure things related to touchpads.

Seems like this is beyond `libinput-gesture`'s scope and has to be dealt with at some other level. Do you know if rotation / configuring for rotation is possible at an even lower level so that it works with `libinput-gesture` directly?

**Comment by bulletmark** [comment]
Well as I said, I think that `rotation` option can be configured via libinput to do what you are saying (if your touchpad had that capability). It has to be lower level than `libinput-gestures` because you would want all your touchpad actions to be "rotated", e.g. ordinary scrolling up/down/left/right which `libinput-gestures` has nothing to do with.
