### ISSUE TITLE
Aviod clicks when gesturing

### ISSUE THREAD

**Issue by OakBaron** [bulletmark/libinput-gestures#204]
Sometimes the gestures cause "ghost clicks" (especially right and middle clicks) to be triggered alongside of (or even instead of) the intended gesture

**Comment by OakBaron** [comment]
Sorry, here's my `libinput-gestures -l`:
`
libinput-gestures: session default+x11 on Linux-4.15.0-46-generic-i686-with-Zorin-12-xenial, python 3.5.2, libinput 1.6.3

/usr/bin/libinput-gestures: hash 4cc3250c5befc6926c04b3e499114677
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
libinput-gestures: device /dev/input/event13: bcm5974
`

**Comment by bulletmark** [comment]
You say "ghost clicks (especially right and middle clicks)" so it seems you are claiming that this utility is generating random mouse clicks?!

Please understand what this simple utility does. It merely reads libinput gestures and actions whatever commands you have configured. Can you see that it not possibly generate "ghost mouse clicks" because it just actions your command and does not do anything with your mouse, or your touchpad, etc.

You seem to have a very generic configuration (and btw, you look to have edited the default `/etc/libinput-gestures.conf` when you really should copy and edit this at `~/.config/libinput-gestures.conf`) so you are only using the stock `wmctrl` and `xdotool` commands so you are in essence claiming that one or both of them are generating random mouse clicks. Experiment with those utilities yourself manually to work out what is going on.

I notice your versions stated above are ancient. The kernel and libinput in particular have added quite a lot of touchpad related fixes since then so I would try and run a more recent system.

**Comment by OakBaron** [comment]
Apologies for being vague. The issue was that the gesture that was switching workspaces was also clicking. I agree that the issue is elsewhere in touchpad settings, I wrongly assumed that everything on my machine was fully up to date and should have checked that first.
Thanks for taking the time to look at and respond to the issue
