### ISSUE TITLE
Provide LICENSE and COPYING

### ISSUE THREAD

**Issue by ElXreno** [bulletmark/libinput-gestures#207]
Hi! Can you provide LICENSE and COPYING on this repo? I'm creating RPM package (COPR [here](https://copr.fedorainfracloud.org/coprs/elxreno/libinput-gestures/)) for Fedora, and for right package these files are required.

P.S. Sorry for my bad English.

**Comment by bulletmark** [comment]
Sorry, any distro specific requirement like that is something the packager (i.e. you) would create/maintain.

I package this for Arch Linux and I maintain the special packaging files which Arch requires elsewhere.

**Comment by ElXreno** [comment]
Oh, okay.
But why, then, in readme.md license information is there, but the license file is not present? I think, it file is needed for any project, who use any license.

**Comment by bulletmark** [comment]
Well the license is clearly stated. Why does it have to be in a specifically named file?

**Comment by ElXreno** [comment]
Sorry, it's only a COPYING file.
"Add a COPYING file with a copy of the GNU GPL or GNU AGPL."
https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by bulletmark** [comment]
So theoretically I am supposed to include a complete copy of the GNU GPL in a file within my source tree. Yuk! I don't see many other programs around github etc including this so it seems to be optional in practice.

**Comment by ElXreno** [comment]
I think a lot of popular free software includes this file in its repository.
This file will not hurt anything if it is in the repository :)

**Comment by bulletmark** [comment]
It will hurt me because it is ugly ;) Imagine if every source tree included a full copy of the GPL, your machine would be littered with hundreds of copies of the same full text.

Debian and derivatives (the largest Linux base) does not include a copy of the license in each package. Rather, each package references the name of the appropriate license of which there is a copy under `/usr/share/common-licenses/`.

Actually, my Arch PKGBUILD file (in my Arch packaging files) nominates the license as "GPL3" and that is a pointer to the file `/usr/share/licenses/common/GPL3` file so essentially I am doing this correctly on Arch via the packaging system so again I suggest it is an issue for you to address. No doubt Fedora would have a similar repository of license files you can reference in your package metadata.

**Comment by bulletmark** [comment]
@rickysarraf yes, I realise that this source repository is probably not compliant with the GNU recommendations and another issue could be raised about that. All files should have a copyright notice in the header etc, include a full copy of the license text, blah, blah.

But that is not what he raised this issue for. He wants to add those 2 specific files for his packaging purposes but they don't really address his packaging issue because he just needs to work out what metadata to add in his packaging files, as I do for Arch.

**Comment by ElXreno** [comment]
@bulletmark okay. Let it be as it was.
