### ISSUE TITLE
Running sudo commands.

### ISSUE THREAD

**Issue by ksmukta** [bulletmark/libinput-gestures#222]
Hi there,
Is it possible to run a command as sudo?

**Comment by bulletmark** [comment]
Libinput-gestures will successfully invoke any command you configure. Whether that command completes successfully and does what you expect it to do is dependent on the arguments you give it, the way you have configured it, and the environment it runs under. Note also the second last paragraph in the CONFIGURATION section of the README. In short, try it! It may fail but that has nothing specifically to do with libinput-gestures.

Note when raising a bug did you miss the massive notes everywhere to always include the output of `libinput-gestures -l` regardless of what the bug is about?!
