### ISSUE TITLE
Swipes register as Pinch

### ISSUE THREAD

**Issue by flycal6** [bulletmark/libinput-gestures#23]
Swipes in all directions are registered as Pinch in and Pinch out ~half the time.

**Comment by bulletmark** [comment]
The determination of what is a _GESTURE_PINCH_ or _GESTURE_SWIPE_ event is completely within libinput. This program just actions commands based on which gestures libinput reports. Run the following libinput utility at the command line to see the gesture reported:

    libinput-debug-events

BTW, you are saying it gets it wrong 50% of the time?! So it is pretty much random for you?

**Comment by flycal6** [comment]
Yes, it's basically random.  `libinput-debug-events` showed a swipe being registered as a pinch more often than not.

**Comment by gaznu** [comment]
Same here. I try every half year or so to setup touchpad and touchscreen gestures. But I always fail due to something or other. 

There seem to exist [no open bug reports](https://bugs.freedesktop.org/buglist.cgi?bug_status=__all__&content=pinch%20swipe&no_redirect=1&order=Importance&query_format=specific) concerning this problem. 

There seems to be a [bug report](https://bugs.freedesktop.org/show_bug.cgi?id=99064) about something similar as reported here. But it requires installing some new beta-kernel and has no real solution but indicates some solution with kernel 4.10 - so I'll wait another half year. 

I post this, because when searching for this problem I always land here first.

**Comment by bulletmark** [comment]
@gaznu reading that bug report you quote seems promising though. Kernel 4.10 may fix your issue, or at least improve things. You don't say what distro you are using but since kernel  4.10 was released a few days ago, it should appear in Arch within a week or two.
