### ISSUE TITLE
kernel bug: Touch jump detected and discarded in ubuntu based 19.10

### ISSUE THREAD

**Issue by REIS0** [bulletmark/libinput-gestures#236]
Getting the kernel bug issue and the gestures don't work at all, tried the troubleshooting and searched for a solution in the closed issues but no progress so far, my machine is an Acer Aspire E5-573G running Pop_OS! 19.10.

```
libinput error: event5  - SYN1B81:01 06CB:7407 Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.14.1/touchpad-jumping-cursors.html for details

```

libinput-gestures -l
```
libinput-gestures: session pop+x11 on Linux-5.3.0-22-generic-x86_64-with-Ubuntu-19.10-eoan, python 3.7.5, libinput 1.14.1
/usr/bin/libinput-gestures: hash 5c8bd05b1deb7a0975b359983e3f1490
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/by-path/platform-INT3432:00-event-mouse(event5): SYN1B81:01 06CB:7407 Touchpad

```

**Comment by bulletmark** [comment]
Ignore that "Touch jump detected" message. As has been mentioned around here a few times, that message is only occasional and benign. I see it and I suspect many/most users also see it. It does not cause any problem.

Did you follow the TROUBLESHOOTING steps? I don't think you tried step 3 because your output above shows you have NO gestures configured which is your problem. Get rid of your custom config and just let it use the generic config. You should be able to switch desktops, e.g. using 3 finger up/down swipes. Once you see that working then copy `/etc/libinput-gestures.conf` to `~/.config/` and edit it as you want.

**Comment by REIS0** [comment]
Yes you were right, since I've installed and didn't edited any file I've guessed it was already using the generic config.
