### ISSUE TITLE
Listen to config file change

### ISSUE THREAD

**Issue by haarp** [bulletmark/libinput-gestures#239]
Hello,

thanks for bringing this to life! Been using it extensively for the past weeks.

What do you think about automatically rereading the config file or restarting libinput-gestures when its config file changes? Lots of other tools have such functionality (devilspie2, alacritty) and it's quite useful. I think all that's needed is setting up an inotify listener on the config.

Thanks!

**Comment by bulletmark** [comment]
Sorry. I do not think this is a good idea. Users should remain in complete control of when the config file is read.  Users rarely change it after initial setup anyhow.

**Comment by haarp** [comment]
I would actually argue that users definitely do tend to change and experiment.

Another argument is that libinput-gestures is usually started at login via autostart. So for less experienced users who can't or don't want to interact with `libinput-gestures-setup` on the commandline, there is no way to change gestures without logging out and back in.

**Comment by bulletmark** [comment]
1. Yes, they do experiment but having a separate terminal window and just executing `libinput-gestures-setup restart` from your command line history is quick, trivial, and predictable. Having the program restart and generate odd error messages just because you saved a transient version of your config file is not sensible in my opinion.

2. Yes, it is usually auto-started. But the only way that can happen is because the user typed `libinput-gestures-setup autostart` originally so he must know about it and how to use it.
