### ISSUE TITLE
[INFO] Made a frontend for libinput-gestures

### ISSUE THREAD

**Issue by GabMus** [bulletmark/libinput-gestures#24]
Hey there, I just wanted to leave a comment here, to let you know that I've created a small GTK frontend for libinput-gestures. I know this is more of a hack than an actual software, but since I've been using it for quite a while, I just thought I could make a simple frontend for it, since editing configuration files frequently can get boring :smile: 

Anyway here you have it, hope you like it!
https://github.com/GabMus/gestureManager

**Comment by bulletmark** [comment]
I personally prefer to edit the text file via my editor as I suspect many would but the animations are a cool looking touch. Some comments:

1. You refer people to the _libinput-gestures-git_ in the AUR but note that was released by somebody else, has never been updated, and is quite out of date now. The official package is _libinput-gestures_ and perhaps best to add the link which is https://aur.archlinux.org/packages/libinput-gestures .That tracks official releases from this repo and is up to date.

2. It only seems possible to add gestures for specific finger configurations. The default (as per the default `libinput-gestures.conf`) is to not specify the finger count so how do you do that? It's a bit of a pain to have to configure each gesture 3 times otherwise.

3. It is customary to add a comment to the top of any generated conf file indicating at least which program generated the file, when it was done, and warning that the file is machine generated etc.

4. There is out some ugly output at the command line, e.g. "ignoring input ..." and a main assert error when terminating.

5. You probably should add a button so a user can reload the new file, i.e. just does a `libinput-gestures-setup restart` and then catch and report errors on that output which will show any conf errors.

I will soon submit a new change to ensure the conf file is more cleanly reported for errors.
