### ISSUE TITLE
create the file not symlink for autostart

### ISSUE THREAD

**Issue by pradhanphy** [bulletmark/libinput-gestures#25]
Create the file  ~/.config/autostart/libinput-gestures.desktop . 
I am using fedora 24 in kde and symlink didn't work.
After copying  the file in ~/.config/autostart/ it worked.

**Comment by bulletmark** [comment]
Seems odd. This obviously works on GNOME but I have also found a few places where it is stated that `~/.config/autostart` symlinks work on KDE5 as well, e.g. https://docs.kde.org/trunk5/en/kde-workspace/kcontrol/autostart/ and https://userbase.kde.org/System_Settings/Startup_and_Shutdown.

Can you please double check this? I am hesitant to just copy the file because then any future changes or additions to the released desktop file will not be reflected automatically for users.

In fact if you just type `libinput-gestures-setup status` you will find that your symlink is restored because I currently specifically want to avoid a file copy. Please then check the symlink created is valid etc.

**Comment by bulletmark** [comment]
OK, I found a good discussion about the issues around this at https://github.com/martinrotter/rssguard/issues/15 so I will consider the solution done there. Note that I already was dealing with `$XDG_CONFIG_HOME` and creating the `autostart` dir, just not the symlink issue.

**Comment by bulletmark** [comment]
I just took the easy option as per your first comment here, i.e. just copy the file now instead of symlink. Just update to the current version and type `libinput-gestures-status status` to fix the `autostart` file.

**Comment by pradhanphy** [comment]
Thanks a lot.
