### ISSUE TITLE
xdotool on Wayland

### ISSUE THREAD

**Issue by nmaggioni** [bulletmark/libinput-gestures#27]
Gnome's 3.22 update silently switched my default session to Wayland, and it took a while for me to notice: many things started to act plain weird out of seemingly nowhere.
In the attempt of fixing _libinput-gestures_ I found out that `xdotool` is not supposed to work in Wayland, but on my system it does; probably because of some leftover XWayland compatibility configuration...?

Anyway, forcing the [ISWAYLAND](https://github.com/bulletmark/libinput-gestures/blob/cb5839e2f2ab1eef40c323743c73700c441d880d/libinput-gestures#L8) variable to `False` brought back my workspace-switching gesture shortcuts without any problem:

```
gesture: swipe up        xdotool key super+Page_Down
gesture: swipe down    xdotool key super+Page_Up
```

Shouldn't `xdotool` support get tested indipendently instead of relying on which graphical server is running?

**Comment by bulletmark** [comment]
Yes, of course if your system can run xdotool then there is no reason for that test to trip you up. Are you running the current version of libinput-gestures? Also, what distribution are you using?

**Comment by nmaggioni** [comment]
I'm running the latest version of the lib from the AUR package, under Manjaro (an Arch derivative).

**Comment by bulletmark** [comment]
I threw that test in quickly so people would know why `libinput-gestures` suddenly stopped working with the transition to Wayland but I guess I will change it to actually run xdotool and confirm it works or not.

**Comment by bulletmark** [comment]
I found I could not reliably test whether `xdotool` runs or not so I just removed the test for Wayland with commit b5d2a335452a20148984a723c657fa1cd0612854. This is updated to the AUR as version 2.8.

**Comment by nmaggioni** [comment]
Sounds fair, thank you for having taken the time to look into this.

**Comment by EAGzzyCSL** [comment]
thank you for your repo, it brought a better experience with gnome， I found four figure swipe to switch workspace has been support in wayland before gnome 3.18 . [here](https://help.gnome.org/misc/release-notes/3.18/more.html.en) is the document。this may be why xdotool not supported on wayland.I install the latest libinput-guesture  from aur and I found I could switch workspace without any realted config in 'libinput-gestures.conf '。 Even if I configed ‘gesture swipe up 4 xdotool key super+Page_up’（super+Page_Up is my short cut to switch to next workspace），it was no effected, when I swiped up in workspace 2,gnome will switch to workspace 3 instead of  worksapce 1, but in xorg it worked. so I think this is controled by gnome rather than libinput-guestures.
sorry for my poor English, hope what I said could bring helps。I am explorering how to disable default guesture feature provided by gnome on wayland。

**Comment by bulletmark** [comment]
@EAGzzyCSL yes I am aware that GNOME on Wayland implements 4 finger swipe up and down to change workspace. In fact, I will add this to the README Wayland notes. My touchpad, like many others, does not support 4 finger gestures. Wayland will never support `xdotool` for native apps because it violates the stricter security model Wayland follows. As the README here says, Wayland currently still supports `xdotool` for all apps like Chrome and Firefox etc which work on Wayland via XWayland but all apps will eventually run on Wayland natively so `xdotool` will eventually not work at all.

I am not sure that you are saying about your configuration? If you are running Wayland why do you want to configure 4 finger swipe to change workspace when it works natively? The default config does not use `xdotool key super+Page_Up/Down` because, as above, that does not work on Wayland so an `_internal` command is implemented which works everywhere.

**Comment by EAGzzyCSL** [comment]
@bulletmark sorry for my confused wayland native app (like gnome on wayland) and xorg based app(like chrome and firefox).I found Two fingers kneading could zoom the web browser so I thought xdotool could work on wayland.

I configure 4 finger swipe to change workspace because I want to change the default behavior( switch from workspace 1 to workspace 2 when swipe up) to switch from workspace 1 to workspace 2 when swipe down.

now I know why `gesture swipe up 4 xdotool key super+Page_up` will made no effect。

really appreciate your patience！

**Comment by qnxdev** [comment]
> Gnome's 3.22 update silently switched my default session to Wayland, and it took a while for me to notice: many things started to act plain weird out of seemingly nowhere.
> In the attempt of fixing _libinput-gestures_ I found out that `xdotool` is not supposed to work in Wayland, but on my system it does; probably because of some leftover XWayland compatibility configuration...?
> 
> Anyway, forcing the [ISWAYLAND](https://github.com/bulletmark/libinput-gestures/blob/cb5839e2f2ab1eef40c323743c73700c441d880d/libinput-gestures#L8) variable to `False` brought back my workspace-switching gesture shortcuts without any problem:
> 
> ```
> gesture: swipe up        xdotool key super+Page_Down
> gesture: swipe down    xdotool key super+Page_Up
> ```
> 
> Shouldn't `xdotool` support get tested indipendently instead of relying on which graphical server is running?

How do I force ISWAYLAND to false?

**Comment by bulletmark** [comment]
@qnxdev, note this bug was from 2016 when Wayland first appeared. Since then libinput-gestures has evolved so nowadays workspace switching should work on both Xorg and Wayland using only the default configuration, as per the README. Please make sure you are using a current version and get rid of your custom configuration. If you still have a problem then please raise a new issue and provide the information stated in the trouble-shooting section.
