### ISSUE TITLE
Moving screen while touching vs moving at release.

### ISSUE THREAD

**Issue by gaspar-d** [bulletmark/libinput-gestures#270]
Hi Mark

I can't found a answer to this on google, I saw videos of some people using gestures on Gnome and the **transition between workspaces was similar as a smartphone**, with the screen moving together with your fingers movement.

But in my **Manjaro Gnome 3.36 xorg** the **action begin as soon as I release the touch**, for example: swipe 3 fingers down and keep the touch, nothing happens, release the touch the workspace change.

It's only a cosmetic behavior, but I'm curious of the why. 

libinput-gestures: session gnome+x11 on Linux-5.6.16-1-MANJARO-x86_64-with-glibc2.2.5, python 3.8.3, libinput 1.15.5
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key control+alt+Down
swipe down       3 xdotool key control+alt+Up
swipe left       3 xdotool key super+Tab
swipe right      3 xdotool key super+Tab
swipe left       4 xdotool key control+shift+Tab
swipe right      4 xdotool key control+Tab
swipe up         4 xdotool key XF86AudioRaiseVolume
swipe down       4 xdotool key XF86AudioLowerVolume
pinch in         4 xdotool key super+s
pinch out        4 xdotool key super+s
pinch in         3 xdotool key control+minus
pinch out        3 xdotool key control+plus
swipe_threshold 100
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event11): ELAN1200:00 04F3:303E Touchpad

**Comment by bulletmark** [comment]
I am unclear what your question is. I think you are asking why the libinput-gestures swipe action to change workspaces is different to the native Wayland swipe action? As it says [in the documentation](https://github.com/bulletmark/libinput-gestures#wayland-and-other-notes), Wayland implements swiping between desktops natively using 4 finger swipes up and down. They have implemented that internally as a gradual transition (like Windows and Mac) but libinput-gestures is a just a simple utility which actions a single command at the end of a swipe or pinch sequence which is why it just switches immediately.

Note you are best to change your swipe up and down 3 finger gestures to the default configurations  which are:
````
swipe up   3 _internal ws_up
swipe down 3 _internal ws_down
````
The above configuration will work the same as the `xdotool` command on Xorg you are using but the `_internal` command will also work if you log in using Wayland. Note that`xdotool` does not work for Wayland desktop or Wayland native apps. If you change that, disable the other swipe up/down for 4 fingers, and log in using Wayland then you can compare the 2 approaches. Note that only laptops of the last 4 years or so can recognise 4 finger touchpad gestures so I have only started trying the Wayland native 4 finger swipe recently and to be honest I still personally favor the 3 finger swipe using libinput-gestures as it just seems snappier to me.

**Comment by gaspar-d** [comment]
I'm sorry, I didn't know this feature is a native from wayland, never used wayland because I hear about issues with nvidia gpu proprietary drivers.

Know I got how stupid my question was.  

BTW, thanks for the advices about my config, I'm done the changes right now.

**Comment by bulletmark** [comment]
Just log out of your current GNOME session, select Wayland from the bottom gear option, then log back in again. Then compare the 4 finger native swipe with the 3 finger swipe and see the difference.

**Comment by gaspar-d** [comment]
I don't have Wayland option, maybe because my proprietary driver, I can just use gnome and gnome classic.

But, something new just happened, I shutdown my laptop yesterday and when I turned him on today I lost my clicks on touchpad and the scroll is reversed, I thought it's some misconfiguration because of gestures but noticed that some gnome extensions disappeared too. 

So I'll try to solve this mistery and after that change my driver's and give Wayland a try. 

Thanks for the help and advices.
