### ISSUE TITLE
GNOME 40 touchpad gestures

### ISSUE THREAD

**Issue by osmanpontes** [bulletmark/libinput-gestures#298]
Hey guys, thanks for this awesome lib.

Recently GNOME released version 40 which includes touchpad gestures.
They are not customizable (at least I didn't find how to) and it's not working so well as your lib.
Trying to run libinput-gestures in GNOME 40 have a conflict once both GNOME and libinput-gestures listen to touchpad events independently.
Like, what I need is disabling GNOME gestures, but I don't know where to ask this.
And I'm writing this to let you know your lib is still important, even after GNOME touchpad gestures was released.

Thanks.

**Comment by bulletmark** [comment]
Thanks. As I say in the README, I created this as a hack 7 years ago after moving from my Mac laptop and only planned to use it temporarily until the Linux DE's added better touchpad support (which is taking much longer than I expected!). I use Arch which updated 2 days ago with GNOME 40 so I already [added a note to the README](https://github.com/bulletmark/libinput-gestures/commit/9138168c25896df34309359b06550f3b7a6e429a) yesterday the new touchpad gestures added by GNOME 40 and warning about avoiding a clash.

Essentially, on GNOME 40 (with Wayland) you are best to remove all 3 finger swipe gestures from your `~/.config/libinput-gestures.conf`. I.e. only use 4 finger swipes and 2, 3, or 4 finger pinches because GNOME (since 40 only) does not use any of those. I personally can't live without the 8 way swipes for my chrome browser to go back/fwd, close/reopen tabs, etc. So I  have just moved them to 4 finger swipes.

**Comment by bulletmark** [comment]
BTW, I also had a quick Google around yesterday about how to disable GNOME 40 gestures but couldn't find anything. I am sure an extension will eventually provide this.

**Comment by osmanpontes** [comment]
Thanks @bulletmark !
I'm using 4 finger swipes too.
I didn't find on Google how to disable GNOME 40 gestures too and then I created question in one of GNOME forums: https://discourse.gnome.org/t/how-to-disable-edit-touchpad-gestures-in-gnome-40/6081.
