### ISSUE TITLE
Running libinput-gestures without the sudo command does not work.

### ISSUE THREAD

**Issue by aad1tya** [bulletmark/libinput-gestures#313]
```
libinput-gestures: session KDE+x11 on Linux-5.13.13-arch1-1-x86_64-with-glibc2.33, python 3.9.6, libinput 1.18.1
Hash: 7b225afc6809da81d306436673af8a29
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event8): SYNA7DB5:01 06CB:CD41 Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart.
libinput-gestures is using custom configuration file.
```

I have followed the installation process exactly as it was described. I am also added to the input group as the user. 
**To make the libinput-gestures work, I have to use the ```sudo libinput-gestures``` command after booting up.** Otherwise the terminal tells me that libinput-gestures is already running, terminating....

```
libinput-gestures is already running for adityak, terminating ..

```

**Comment by bulletmark** [comment]
Paste the output of the command `id` here please.

Note you have created a custom configuration file but you have not  put any commands in it so `libinput-gestures` will not do anything.

**Comment by aad1tya** [comment]
```
uid=1000(adityak) gid=1001(adityak) groups=1001(adityak),3(sys),10(wheel),983(rfkill),987(users),996(input)

```
Yes, you are right. I haven't put any commands in it but when I run the libinput-gestures with the sudo command, there are already some default gestures that work out of the box without me adding anything. For example, three fingers swipe up changes the desktop.

**Comment by bulletmark** [comment]
DE's and libinput-gestures should never be run as root so forget about doing that. It is not relevant here. From what you have shown above, libinput-gestures is running completely as normal because you have nothing configured for it to do. Please delete that `~/.config/libinput-gestures` file and then `libinput-gestures-setup restart` then it will use the default configuration file. If you see those working then add a custom configuration file (with commands this time!) and try again. If you have an issue at any time then please follow the [TROUBLESHOOTING](https://github.com/bulletmark/libinput-gestures#troubleshooting) section.

**Comment by bulletmark** [comment]
BTW, whenever you paste output, **always** include the initiating command in that output to give context. E,g, you quote that `libinput-gestures is already running` output above but I do not know what you did to cause that message to be output.

**Comment by aad1tya** [comment]
Okay. I'll do what you mentioned. Thanks for replying and the helpful tip.

**Comment by bulletmark** [comment]
Why did you close the bug? Did you find the problem?
