### ISSUE TITLE
How to Change Audio Volume and Music Track with xdotool?

### ISSUE THREAD

**Issue by Msadr471** [bulletmark/libinput-gestures#340]
I saw the example in the `libinput-gestures.conf` but this has a problem it doesn't keep decreasing or increasing when I swipe up or down my fingers! [help](https://elementaryos.stackexchange.com/questions/3195/xdotool-keypress-and-key-release)
```
# Example to change audio volume:
# Note this only works on an Xorg desktop (not Wayland).
gesture swipe up   xdotool key XF86AudioRaiseVolume
gesture swipe down xdotool key XF86AudioLowerVolume
```
Another thing is what are the xdotool commands for the next track and the Previous track like (XF86AudioLowerVolume)?  I couldn't find them!
some thing like this:
```
# Example to change audio volume:
# Note this only works on an Xorg desktop (not Wayland).
gesture swipe left   xdotool key XF86AudioNextTrack
gesture swipe right xdotool key XF86AudioPreviousTrack
```
thanks

**Comment by bulletmark** [comment]
Sorry, but the current implementation only supports a single volume step for each swipe. Long ago, I did have a branch that allowed an analog "scale" parameter based on the size of the swipe but it never got traction and it fell by the wayside.

Note that this bug prompted me to add a better  example to the sample conf file to use `amixer` instead of `xdotool` so you can at least set the size of the volume movement and it also works on both Wayland and Xorg. See commit b26ec95.
