### ISSUE TITLE
Config option to start action when gesture starts

### ISSUE THREAD

**Issue by guiodic** [bulletmark/libinput-gestures#354]
It would be useful to be able to configure libinput-gestures to start the action when the gesture starts, with a configurable delay.

Thanks!

**Comment by bulletmark** [comment]
Please explain why you think anybody would want that? If you want a quicker gesture just move your fingers quicker and/or for a shorter distance.

This program relies completely on libinput to decide and discriminate what [gestures are](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html). It doesn't decide the direction (e.g. of the 8 swipe candidates) until libinput says the gesture is completed (i.e. when the users' fingers are lifted) because the user can change their mind, e.g. they can _swipe left_ slightly and then _swipe right_ significantly before they lift their fingers and since this program looks only at the absolute distance traveled at that end then it knows it was a _swipe right_, not a _swipe left_. This can be a subtle difference, e.g. between a _swipe left_ and a _swipe left_down_. Or they can move their fingers back to approximately where they started from to "cancel" the gesture because this program requires a threshold movement.

**Comment by bulletmark** [comment]
No response from OP so closing.
