### ISSUE TITLE
xdotool key super doesn't works

### ISSUE THREAD

**Issue by jbtrystram** [bulletmark/libinput-gestures#41]
I cannot get the "pinch to expose all windows" work on fedora 25. It looks like it's related to xdootol since if I run `xdotool key super` in a terminal there is no output. 

According to this bug [1] it looks like the support of aliases in xdotool might have been dropped. 
I tried several things (like `xdotool key Super` or  `Super_L`) but no success. When running `xev` then pressing the super key... well, the activities show up and nothing shows up in xev. 
It might be a bug in gnome or fedora though

[1] : askubuntu.com/questions/695017/why-does-my-xdotool-key-command-not-work

**Comment by jbtrystram** [comment]
oh, looks like it is the same as in #28, #27 and #26 won't work in wayland.
What's straange though : swipe left and right works in firefox, but not in nautilus. Pressing Alt+arrow works in both cases.

**Comment by bulletmark** [comment]
`xdotool` can not work for native Wayland apps as Wayland does not provide the hooks for `xdotool` and never will as it imposes a stricter security model. So this includes all stock GNOME apps like terminal, nautilus, etc where `xdotool` is of no use. However, `xdotool` does work for any apps which run on Wayland via XWayland, e.g. Chrome and Firefox browsers. That is why the default `libinput-gestures.conf` now defines `xdotool` for page forward/back in those browsers, and uses `wmctrl` (via the `_internal` command) to do workspace switching since that tool can switch workspaces both on Xorg and on Wayland (via XWayland). This gives uses the 2 most useful gestures, i.e. swipe between workspace and page fwd/back in the browser which work in both Xorg and Wayland environments.
