### ISSUE TITLE
Default Config duplicated function

### ISSUE THREAD

**Issue by 89luca89** [bulletmark/libinput-gestures#46]
Hi, I noticed that by default the pinch-in/out is equivalent:
```

gesture: pinch in dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'

gesture: pinch out dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'
```

This way, If I do a pinch-in twice it will show/hide, but it's a rather strange behaviour

In my personal config I use:

```
gesture: pinch in dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.hide();'

gesture: pinch out dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.show();'
```

And it behaves in a much more "natural" way, can I suggest to change this? It seems a much more sane default to me.

Thanks a lot for this tool! It changed completely the use I do of my touchpad! Thanks!

**Comment by bulletmark** [comment]
The two pinch gestures have been configured the same action to toggle the overview since the very first version of this program. Actually, when I tried your config I initially thought it was configured around the wrong way! The gesture to "pinch in" should arguably show the overview, not close it? My experience shows the disadvantage of configuring it one way or the other because some people will inevitably prefer the other way, or have already committed it to muscle memory. Having it a toggle avoids this problem with no real disadvantage.
