### ISSUE TITLE
2-finger gestures

### ISSUE THREAD

**Issue by Irdisss** [bulletmark/libinput-gestures#48]
Thanks for a great app. Is it possible to somehow enable 2-finger gestures? I know it uses DE, but maybe somehow it is possible? Interested in Unity, ubuntu 16.10.

**Comment by bulletmark** [comment]
The definition of a gesture is completely defined by libinput, not by this app. Run the following to see what I mean and try various one, two, or more finger movements. This will run `libinput-gestures` to just print out the raw events that libinput outputs to this app.
~~~~
libinput-gestures-setup stop
libinput-gestures -r
~~~~~

This app only processes the `GESTURE_*` events which you will see are only reported by libinput for 2 or more finger pinches, and then 3 or more finger swipes. All _libinput-gestures_ does is map those `GESTURE_*` events into command actions from the config file. That's it, yes it is a very simple app. The `GESTURE_*` events are currently ignored so that is why I created this app, at least until we see DEs and app supporting `GESTURE_*` events natively. 

I guess theoretically I could enhance it to also try to interpret standard `POINTER_MOTION` events but that is fraught with complication given that most 2  finger actions are already interpreted by the DE and apps for scroll etc.
