### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by Chrysostomus** [bulletmark/libinput-gestures#56]
I tried to recreate rudimentary pinch to zoom by binding pinch motions to xdotool events ctrl+plus and minus. However, this leads to very unintuitive zooming, because each pinch motion only generates one event. 

Would it be feasible to implement pinch to zoom through this project, or would it complicate the code unnecessarily?

**Comment by Chrysostomus** [comment]
I don't know python myself, but what I gather from lines 211-227, the direction of the pinch is calculated only when the motion ends. I would imagine that calculating it on pinch update events would be much more costly,  as those events are far more numerous. I tried writing a dash script alternative to this, but could not properly figure out how to calculate pinch direction from single pinch update event.

**Comment by bulletmark** [comment]
Yes, this application simply accumulates numbers at each libinput update and only actions the command when the gesture is completed. This is simple and the system performance overhead is tiny. I don't really want to make any significant architectural change like you suggest for something based on `xdotool` because it is essentially at a dead end given we are all moving to Wayland where `xdotool` does not work and never will. Arch (which I use) and Fedora already use Wayland by default for GNOME now.

Be aware that gestures can not, in general, be interpreted at a global level anyhow, certainly this is true for pinch. Gestures should be forwarded to individual applications which action them based on context. Note that pinch to zoom is already implemented in some apps on GNOME on Wayland, e.g. the standard document viewer (evince) will zoom in/out on pinch which is the reason, e.g, that I personally disable global pinch in my `libinput-gestures.conf` file. So I only enable swipes up/down to switch workspaces, and swipe left/right for browser back/forward. As I say in the README here, `libinput-gestures` is only a stop-gap solution until the DEs and apps implement gestures themselves and they are getting there.

**Comment by Chrysostomus** [comment]
Thanks, I figured as much and it makes sense. Could you explain to me how the calculation for the pinch direction, so I can figure out how to implement it myself? I personally use this in bspwm, which is unlikely to be ported to Wayland any time soon, and is too minimalistic to handle gestures by itself. 

Some value from pinch update events is collected to an array, and they summed up with each other and then deducted from 1? Is it something like that?

**Comment by bulletmark** [comment]
The update function is called very frequently as a gesture is in progress and then the end function is called when the gesture is completed. So you would/may want to action your xdotool command every now and then from the update function based on distance moved etc. I'd avoid calling xdotool every update() as it would likely perform poorly.

**Comment by Chrysostomus** [comment]
Thanks
