### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by nos1609** [bulletmark/libinput-gestures#6]
Maybe it would be better to make this as an AUR package with all deps etc?

**Comment by bulletmark** [comment]
It's not specifically for Arch Linux. It probably works on nearly all linux distros. It only requires python 3, a modern version of libinput, and the xdotool utility. So the dependencies are trivial.

I do maintain one other AUR package so I will think about adding this.

**Comment by adrfantini** [comment]
I agree an AUR package would indeed be handy.

2016-03-11 22:55 GMT+01:00 Mark Blakeney <notifications@github.com>:

**Comment by Edenhofer** [comment]
I would be more than happy to package libinput-gestures for Arch Linux. However in its current form it can not be installed to folder residing outside of `/home` which is forbidden to touch for a package manager. Therefore I recommend that the installation and configuration to be made more generic: install .desktop files which should be automatically started at boot to `/etc/xdg/autostart/`, configuration files to e.g. `/etc/conf.d` and additional script and files to `/usr/lib`.

**Comment by bulletmark** [comment]
Ok, I promise I will add this to the AUR in the next week or so. It will install to system dirs.

**Comment by Edenhofer** [comment]
I create a *hacked* solution which should work just fine for most of the people. It is available as an [AUR package](https://aur.archlinux.org/packages/libinput-gestures/).
For now the only valid configuration file is `/etc/conf.d/libinput-gestures.conf` in order to be more generic assuming this is ok for most people. Additionally the PKGBUILD builds this software by using the commit hash since currently there is no version reference or tag in this repository. But besides those mentioned 'downsides' the software works great!

@bulletmark If you wish to take over maintenance I will of course disown the package otherwise I would be happy to maintain it. Thanks for creating this peace of software!

**Comment by bulletmark** [comment]
I have started working on this but really would prefer to use the libinput-gestures package name which you have taken. You are free to create your own version of course but can you call it something else?

**Comment by Edenhofer** [comment]
I disowned the package...

**Comment by bulletmark** [comment]
Please submit a deletion request rather than just a disown because I prefer to be accredited as the original submitter.

**Comment by Edenhofer** [comment]
OK, if this really is important to you... done. The package was immediately removed from the AUR.

**Comment by bulletmark** [comment]
Commit c48357f06ca70ad286828f82cfe4d3bfb87dac34 refactors the code to prepare it for the AUR package I will soon add.

**Comment by bulletmark** [comment]
This is now completed since final commit 3c9f4700da54e4618f906d0b3874129457e05df4.
