### ISSUE TITLE
Xdotool problem

### ISSUE THREAD

**Issue by matjaz132** [bulletmark/libinput-gestures#61]
I have hotkey on GNOME 3.22 to minimize a windows on Super+H but when I use super+h in config it firsts type letter "h" and then I have to reuse the gesture to hide a windows.

Any fix for this?

**Comment by bulletmark** [comment]
I am sorry but I can't really help you here on how to use `xdotool`. Read the man page, check the web, and experiment on the command line to get it working then paste that exactly to a gesture line in your `~/.config/libinput-gestures.conf`.

BTW, since gnome 3.22, many distros use Wayland by default where `xdotool` will not work for desktop shortcuts. `xdotool` will only work for Xwayland client apps.
