### ISSUE TITLE
Feature Request: Rotate

### ISSUE THREAD

**Issue by GIJack** [bulletmark/libinput-gestures#74]
Great Projects BTW. I just have one feature request:

Rotate

I would like to see a rotate event as well.

**Comment by bulletmark** [comment]
Libinput signals rotation as a pinch event but I guess I can add some threshold logic to decide if the pinch is in or out (as now), or clockwise or anticlockwise. I have thought about doing this before but thought it would be awkward to use. However, since you asked and it would not be hard to add, I will give it a go.

I will probably create a special branch and ask you to test and comment. I will make it that if a user does not configure these extra pinch gestures then behavior will remain as now which is the same as I recently did when adding optional swipe left_up, left_down, etc.

**Comment by bulletmark** [comment]
I have pushed a new branch called rotation which you can try. The new gestures are `pinch clockwise` and `anticlockwise`. With my touchpad at least they seem to be reported a little unreliably by libinput which you can see by looking at the raw libinput events with `libinput-gestures -r`.

**Comment by bulletmark** [comment]
OP never got back to me. Have pushed this change to master and AUR.

**Comment by Vistaus** [comment]
I added pinch clockwise and anticlockwise to my config file and then restarted libinput-gestures, but rotating doesn't work for me in GThumb. Maybe I've done something wrong? This is what I've added at the end of /etc/libinput-gestures.conf

gesture swipe pinch clockwise xdotool key r
gesture swipe pinch anticlockwise xdotool key shift+r

(those shortcuts are used for rotating in GThumb)

OS: Solus
DE: Budgie

Other gestures, like browser go back/forward, are working fine.

**Comment by bulletmark** [comment]
@Vistaus I've never tried the pinch clockwise and anticlockwise gestures myself but I just installed gthumb and configured your gestures above and they worked fine. Obviously `xdotool` will never work under Wayland so please confirm you are using Xorg. Please paste the output of `libinput-gestures -e` here (as per step 7 of the TROUBLESHOOTING section in the README).

**Comment by Vistaus** [comment]
I am using Xorg. Like I said: the other gestures are working fine.

This is the output of libinput-gestures -e:

```
[11:29:54] vistaus@vistaus-solus /media/MicroSD/Apps (0)
> libinput-gestures -e
libinput-gestures: device /dev/input/event10: SYNA0000:00 06CB:7AB3
libinput-gestures: session budgie-desktop+x11 on Linux-4.9.30-29.lts-x86_64-with-glibc2.3.4, python 3.5.2, libinput 1.7.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures
[11:29:55] vistaus@vistaus-solus /media/MicroSD/Apps (0) 
> 
```

**Comment by bulletmark** [comment]
Gesture handling is generic so if the others are working, and you don't get errors reported, then the problem is likely to do with your hardware. Those pinch rotations work for me but they are admittedly quite awkward to cleanly invoke with my touchpad. I use extended swipe gestures to close/reopen/switch tabs etc and they work well but I personally do not configure any extended pinch gestures. Perhaps pinch rotations are near impossible to invoke on your specific touchpad. Run `libinput-gestures -r` in a terminal to see if you can raises PINCH gestures at all when doing an exaggerated rotation with 2 fingers. Those raw messages are reported by libinput directly so if you can't invoke PINCH gestures doing finger rotations then  libinput is not reporting them for your touchpad and there is nothing this utility can do about that.

**Comment by Vistaus** [comment]
Actually, thanks to your suggestion of running libinput-gestures -r again, I now noticed that it uses a config file my .config folder even though up till now I had it configured system-wide. So now I moved the pinch stuff from the system-wide file to the file in .config and libinput-gestures reports the following:
```
[16:03:19] vistaus@vistaus-solus /home/vistaus/Downloads (0)
> libinput-gestures -r
Error at line 84 in file /home/vistaus/.config/libinput-gestures.conf:
>> gesture swipe pinch clockwise xdotool key r <<
Gesture swipe does not support motion "pinch".
Must be "left" or "right" or "up" or "down" or "left_up" or "right_up" or "left_down" or "right_down".
[16:03:22] vistaus@vistaus-solus /home/vistaus/Downloads (1) 
> 
```

**Comment by bulletmark** [comment]
Now that you have fixed your config error, run `libinput-gestures -d` at the command line and see what it would be actioning.

**Comment by Vistaus** [comment]
```
[10:46:02] vistaus@vistaus-solus /home/vistaus (127) 
> libinput-gestures -d
libinput-gestures: device /dev/input/event12: SYNA0000:00 06CB:7AB3
libinput-gestures: session budgie-desktop+x11 on Linux-4.9.32-30.lts-x86_64-with-glibc2.3.4, python 3.5.2, libinput 1.7.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 8 gestures
libinput-gestures is already running for vistaus, terminating ..
[10:46:02] vistaus@vistaus-solus /home/vistaus (1) 
> 
```

**Comment by Vistaus** [comment]
WAIT A SEC! Now that I've ran libinput-gestures -d, rotating in GThumb works!
Although I must say that rotating clockwise seems to go easier than rotating count-clockwise. Not sure why that's more tricky? But I'm glad it works now, thank you so much for all of your help! 😄

**Comment by bulletmark** [comment]
Like I said, pinch rotation doesn't work that well. At best, consider it experimental.
