### ISSUE TITLE
gestures registering, but not changing workspace

### ISSUE THREAD

**Issue by joseywallace** [bulletmark/libinput-gestures#76]
Hello,

I'm trying to get gestures working on my xps 13 9360 on ubuntu 16.04. I followed the instruction here:
https://github.com/bulletmark/libinput-gestures
as well as the troubleshooting suggestions, but can not get it to work fully. Interestingly, the debug mode (-d) shows the trackpad is registering the gestures and even repeats back to me the correct key patterns.  Additionally, the -v mode shows all as the input source. I can get the browser backward and forward to work, but not the workspace switching. I think this may be due to my workspace layout, which was configured in Compiz to be 3 column by 2 rows. I tried both the default config file and tried modifying the config file to:

gesture swipe up	_internal --col=3 ws_up
gesture swipe down	_internal --col=3 ws_down
gesture swipe left	_internal --row=2 ws_up
gesture swipe right	_internal --row=2 ws_down

Is this the correct modification for a 3x2 workspace configured in compiz? What else could be the problem?

Thanks in advance for any help.

**Comment by bulletmark** [comment]
There is an example configuration in the default `libinput-gestures.conf` for 2 rows of 4 columns but your configuration is not consistent with that. Have another look there but in short, swap your 2's and 3's.

**Comment by bulletmark** [comment]
I should add that, as the example in `libinput-gestures.conf` says, you have to also ensure you configure your KDE virtual desktops to match the same rows x columns.

**Comment by joseywallace** [comment]
I tried the suggestions (I think). Are compiz virtual desktop and kde
different? Is this program designed to work in ubuntu 16.04 (gnome) or only
kde environment?

**Comment by joseywallace** [comment]
oops sorry actually unity environment.

**Comment by bulletmark** [comment]
As per the TROUBLESHOOTING section in the README, paste the output here of `libinput-gestures -d` and `libinput-gestures -l`.

I develop and test this utility on GNOME on Arch Linux but it should work on every desktop on every Linux.

**Comment by joseywallace** [comment]
libinput-gestures: device /dev/input/event11: DLL075B:01 06CB:76AF Touchpad
libinput-gestures: session ubuntu+x11 on
Linux-4.8.0-46-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2,
libinput 1.2.3
libinput-gestures: using /etc/libinput-gestures.conf with 4 gestures
libinput-gestures: SWIPE up 3 [-105.54000000000002, -381.96]
   _internal --col=2 ws_up
libinput-gestures: SWIPE right 3 [668.74, -58.510000000000005]
   _internal --row=2 ws_down
libinput-gestures: PINCH in 3 [-0.4500000000000002, -3.67]
libinput-gestures: SWIPE down 3 [39.08, 385.22]
   _internal --col=2 ws_down



Gestures configured in /etc/libinput-gestures.conf:
pinch in         <not configured>
pinch out        <not configured>
pinch clockwise  <not configured>
pinch anticlockwise <not configured>
swipe left       _internal --row=2 ws_up
swipe right      _internal --row=2 ws_down
swipe up         _internal --col=2 ws_up
swipe down       _internal --col=2 ws_down
swipe left_up    <not configured>
swipe right_up   <not configured>
swipe left_down  <not configured>
swipe right_down <not configured>


Thanks for your help with this!

**Comment by bulletmark** [comment]
I don't use Unity and am unfamiliar with it. Given you have changed your libinput-gestures config to 2x2 does that mean you changed your Unity virtual desktops to 2x2 as well? You have to keep them in sync.

Please set up the virtual desktops as you want in Unity, e.g. 2x2 or 3x2 or 2x3 etc. Then paste the output here of `wmctrl -d`.

Note please avoid replying to github email. Much better to reply on the actual github issues page (https://github.com/bulletmark/libinput-gestures/issues/76) so we can format fixed text etc. I edited your comments about to remove all the reply guft but I can't add code tags because you are replying in email.

**Comment by joseywallace** [comment]
Thanks will do! I did change to a 2x2 grid.
Here is the output:

0  * DG: 3840x2160  VP: 0,0  WA: 0,36 1920x1044  N/A

**Comment by bulletmark** [comment]
OK, I am surprised that nobody has ever reported this before but the `_internal` command in `libinput-gestures` will not work with Unity/Compiz because `wmctrl` does not list and select desktops correctly with Compiz as per http://askubuntu.com/questions/41093/is-there-a-command-to-go-a-specific-workspace.

As per the top answer there, I can probably work around this by detecting Compiz and then using the `wmctrl -o` option to select the viewport. Unfortunately I don't have access to a Unity system to try this out and given todays news that Ubuntu is ditching Unity to go back to GNOME I am not sure it is worth me addressing. I will think about it some more.

**Comment by bulletmark** [comment]
Of course as a workaround you can change your config to use Unity keyboard shortcuts to move between desktops and not use the `_internal` command. That is your best approach. Just configure swipe up/down/left/right to ctrl+alt+up/down/left/right.

**Comment by joseywallace** [comment]
I saw somewhere that your config file had been adapted to:

gesture: swipe left 3 swaymsg -t command workspace next_on_output

but im not sure if this makes any sense for me to use.

Thanks for your help and patience!!

**Comment by joseywallace** [comment]
Wow! Thanks that worked!
here are the bindings in case anyone wants to copy and paste:

gesture swipe up	xdotool key ctrl+alt+Up
gesture swipe down	xdotool key ctrl+alt+Down
gesture swipe left	xdotool key ctrl+alt+Left
gesture swipe right	xdotool key ctrl+alt+Right

Thanks again!!

**Comment by bulletmark** [comment]
Thanks. I will add those commands commented out with some words in the `libinput-gestures.conf` as an example for Unity users.

**Comment by bulletmark** [comment]
Addressed with commit d0bf9e0aef23cb46c2b5191ed62fc3748303bab8.
