### ISSUE TITLE
get it on User repos 

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [bulletmark/libinput-gestures#85]
If you leave this amazingly useful app on github, it would be hard for many to install & update it. I have (kind of) fixed that with creating a "Touchpad Updater" but it would be much better if you converted it into a PPA, or maybe a flatpak, or a snap!

**Comment by bulletmark** [comment]
I do maintain it as a package for Arch Linux at https://aur.archlinux.org/packages/libinput-gestures/.

I wouldn't mind also maintaining a Debian package but since I don't have access to a Debian or Ubuntu environment it is too difficult. 

It seems there were a couple of guys maintaining packages for Fedora at https://copr.fedorainfracloud.org/coprs/galaticstryder/libinput-gestures/ and https://copr.fedorainfracloud.org/coprs/mhoeher/multitouch/ but neither have been updated for ages and are way out of date.

**Comment by Vistaus** [comment]
Solus also packaged libinput-gestures and it receives updates, albeit a little slow. But still, today us Solus users finally got the 2.23 update.

**Comment by mhoeher** [comment]
Hi @bulletmark,

I am the maintainer of one of the above Fedora repositories. I just updated to the most recent version 2.24, the Copr build is still running but afterwards users should be able to update via the repository.

A question on update notifications: Do you maintain any communication channel to notify people about new releases of libinput-gestures? The only thing GitHub seems to provide is some RSS/Atom feed for the releases.

**Comment by bulletmark** [comment]
@mhoeher  No sorry, the github notification is the only way. I only tagged a new release 2.24 because it has been a couple of months since the last release but there is almost nothing functionally different.
