### ISSUE TITLE
Make gesture command happen on the fly

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [bulletmark/libinput-gestures#89]
BUG: Lets start with an example.
In Mac OS X, When you switch workspaces with the touchpad, the workspaces move **dynamically** depending on the touchpad. Fast Forward to Libinput-gestures, where once the touchpad gestures is done, only then the gesture swifts across the workspace. I knoe the part of the workspaces dynamically moving needs to be done inside GNOME / KDE, but can you make it that after a specific time, even if the fingers are not of the touchpad, the gestures does the command? soft of like Windows 10 and three fingers up takes you to the multitask menu, whereas with it and the gestures, while you are doing the touchpad gesture, the command happens, not afterwards.

**Comment by bulletmark** [comment]
You can't call this a bug. Ultimately this is a cheap hack to give fairly crude functionality to switch workspaces using your touchpad. I agree it is not a nice as the way Mac OS X does it but GNOME and KDE etc do not provide any hooks to progressively slide the workspace so there is nothing I can do about that. Your suggestion for a timeout would not really make much difference because most people just do a short quick swipe anyhow so a timeout is irrelevant. Also, libinput allows you to change your mind and "cancel" a gesture before you raise your fingers and `libinput-gestures` respects that cancel. Adding a timeout could action the switch before the cancel.

I also used to use a Mac and that is what prompted me to create this simple utility. `libinput-gestures` may not ba as slick as Mac OS X but it is much better than nothing and at the end of the day it provides the same essential functionality.
