### ISSUE TITLE
Thanks so much

### ISSUE THREAD

**Issue by 1Claude** [bulletmark/libinput-gestures#90]
It's not an issue or a request. I just wanted to thank you for libinput-gestures. So cool to finally use swipe gestures in Gnome to go forward or backward in a web browser, and change desktop.

PS : I modified the 3 fingers swipe, left to go back, and right to go forward. Seems more fingers logical to me.  :-)

**Comment by bulletmark** [comment]
If you prefer to reverse the direction of swiping left and right then did you also reverse up and down? Do you configure you touchpad to use natural scrolling? I think it is consensus now that Apple got it right by reversing touchpad scroll direction in 2011 and I think most people prefer it that way now which is why I set the default directions for left/right and up/down as I did.

I may add a note in the README about reversing these if they don't use natural scrolling direction.

**Comment by 1Claude** [comment]
No, I don't use reverse (or natural) scrolling. That's the first thing I 
do : uncheck that option. And add Tap to click.

Scroll up to the next desktop is fine with me. I only have 2 desktops.
